<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <OutputPath>$(MSBuildThisFileDirectory)BuildOutput\plugins\K4-WorldText-API\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="K4-WorldText-SharedAPI\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.369">
      <PrivateAssets>none</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <ProjectReference Include="K4-WorldText-SharedAPI\K4-WorldText-SharedAPI.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <Target Name="ExcludeSharedApiFiles" AfterTargets="Build">
    <Delete Files="$(OutputPath)K4-WorldText-SharedAPI.dll" />
    <Delete Files="$(OutputPath)K4-WorldText-SharedAPI.pdb" />
    <Delete Files="$(OutputPath)K4-WorldText-SharedAPI.deps.json" />
  </Target>

</Project>